import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'

// Styles
import styles from '../styles/index.module.css';
import headerStyles from '../styles/header.module.css';
import sidebarStyles from '../styles/sidebar.module.css';

// Images
import profileSvg from '../assets/profile.svg';
import bagSvg from '../assets/bag.svg';
import { createContext, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

interface UserContextInterface {
  id_usuario: null | number;
  updateUsuario: (userId: number) => void; 

}

export const UserContext = createContext({});


export default function App({ Component, pageProps }: AppProps) {

  const changeUser = (userId: number) => {
    setUserState(() => {
      return{
        id_usuario: userId,
        updateUsuario: changeUser
      }
  })}
  const [userState, setUserState] = useState<UserContextInterface>({ id_usuario: null, updateUsuario: changeUser })

  return (
    <>
      <Head>
        <title>Mercadolibre App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
            <div id={styles.webBody}>
                <header className={headerStyles.yellowHeader}>
                    <img className={headerStyles.mercadolibreLogo} src="https://http2.mlstatic.com/frontend-assets/ml-web-navigation/ui-navigation/5.21.21/mercadolibre/logo__large_plus@2x.png"></img>
                    <a className={headerStyles.profileLink} href={`/profile`}>
                        <Image src={profileSvg} alt="Profile Icon SVG" className={headerStyles.profileIcon} priority />
                        <p>Mi Perfil</p>
                    </a>
                </header>
                <section className={sidebarStyles.sidebar}>
                    <a className={sidebarStyles.sidebarItem} href={`/profile`}>
                        <Image src={profileSvg} alt="Profile Icon SVG" priority />
                        <p>Informacion General</p>
                    </a>
                    <a className={sidebarStyles.sidebarItem} href={`/purchase-list`}>
                        <Image src={bagSvg} alt="Bag SVG" priority />
                        <p>Mis Compras</p>
                    </a>
                </section>
                <section className={styles.mainBody}>
                  <UserContext.Provider value={userState}>
                    <Component {...pageProps} />
                  </UserContext.Provider>
                </section>
            </div>
        </main>
    </>
  )
}
