import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import Image from 'next/image'
import { Montserrat } from '@next/font/google'
import { useState } from 'react'

// Styles
import styles from '../styles/index.module.css';
import headerStyles from '../styles/header.module.css';
import sidebarStyles from '../styles/sidebar.module.css';

// Images
import profileSvg from '../assets/profile.svg';
import bagSvg from '../assets/bag.svg';
import burgerMenuSVG from '../assets/burgerMenu.svg';
import { ErrorBoundary } from '@/shared/errorBoundary'

const montserrat = Montserrat({ subsets: ['latin'] })


export default function App({ Component, pageProps }: AppProps) {

  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Mercadolibre App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={montserrat.className}>
            <div id={styles.webBody}>
                <header className={headerStyles.yellowHeader}>
                    <img className={headerStyles.mercadolibreLogo} src="https://http2.mlstatic.com/frontend-assets/ml-web-navigation/ui-navigation/5.21.21/mercadolibre/logo__large_plus@2x.png"></img>
                    <a className={headerStyles.profileLink} href={`/profile`}>
                        <Image src={profileSvg} alt="Profile Icon SVG" className={headerStyles.profileIcon} priority />
                        <p>Mi Perfil</p>
                    </a>
                    <Image onClick={() => { setIsSidebarOpen(true) }} className={headerStyles.burgerMenuIcon} src={burgerMenuSVG} alt="Burger Icon" priority />
                </header>
                <section className={`${sidebarStyles.sidebarOverflow} ${isSidebarOpen ? sidebarStyles.active : ''}`}>
                  <div className={sidebarStyles.sidebar}>
                        <div className={sidebarStyles.closeIcon}>
                            <p onClick={() => { setIsSidebarOpen(false) }} >X</p>
                        </div>
                        <a className={sidebarStyles.sidebarItem} href={`/profile`}>
                            <Image src={profileSvg} alt="Profile Icon SVG" priority />
                            <p>Informacion General</p>
                        </a>
                        <a className={sidebarStyles.sidebarItem} href={`/purchase-list?offset=0&limit=10`}>
                            <Image src={bagSvg} alt="Bag SVG" priority />
                            <p>Mis Compras</p>
                        </a>
                  </div>
                </section>
                <section className={styles.mainBody}>
                    <ErrorBoundary >
                      <Component {...pageProps } />
                    </ErrorBoundary>
                </section>
            </div>
        </main>
    </>
  )
}
