version: '3.7'
services:  
  #server_mercadolibre:
  #  image: mlibre-api:latest
  #  ports:
  #    - 8050:8050
  #  depends_on:
  #    - cache
  #  volumes:
  #    - /logs-pool/pm2:/var/log/pm2
  #  networks:
  #    - mlibre-net
  
  cache:
    image: redis:6.2-alpine
    restart: always
    hostname: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
  
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: cache
      REDIS_HOST: cache
      REDIS_PORT: cache:6379
      HTTP_USER: root
      HTTP_PASSWORD: root
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - 8081:8081
    #networks:
    #  - mlibre-net

volumes:
  cache:
    driver: local

#configs:
#  nginx.conf:
#    file: ./nginx/${CI_ENVIRONMENT_SLUG}.conf

networks:
  mlibre-net:
    driver: overlay